# Generated by Django 2.1.5 on 2019-03-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20190321_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favourite_songs',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='music.Song'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
